In [ ]:
%pip install pandas numpy gensim nltk


In [34]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [35]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [36]:
for file in os.listdir('./data/'):
    print(file)


story1.txt
story2.txt


In [37]:
f=open(r"C:\src\pyprojects\Full-Stack-GenAI-Bootcamp-1.0\04-12-2026\data\story1.txt",encoding='unicode_escape')


In [38]:
corpus = f.read()

In [39]:
print(corpus)

Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers. He was very curious about how things worked and always asked questions. His parents often smiled at his curiosity and encouraged him to learn more.

Every day after school, Arjun would sit with his books and explore different topics. He was especially fascinated by science and technology. He wanted to understand how machines think and whether they could become as intelligent as humans.

One day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence. He read about how machines can learn from data, recognize patterns, and even make decisions. This idea completely amazed him.

He started imagining a future where machines could help humans solve complex problems. That day, he made a decision that he wanted to become an AI engineer.

Arjun began learning programming using free resources. At first, everything seemed difficult. He st

In [40]:
sent_tokenize(corpus)

['Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers.',
 'He was very curious about how things worked and always asked questions.',
 'His parents often smiled at his curiosity and encouraged him to learn more.',
 'Every day after school, Arjun would sit with his books and explore different topics.',
 'He was especially fascinated by science and technology.',
 'He wanted to understand how machines think and whether they could become as intelligent as humans.',
 'One day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence.',
 'He read about how machines can learn from data, recognize patterns, and even make decisions.',
 'This idea completely amazed him.',
 'He started imagining a future where machines could help humans solve complex problems.',
 'That day, he made a decision that he wanted to become an AI engineer.',
 'Arjun began learning programming using free resources.',


In [41]:
raw_sent = sent_tokenize(corpus)

In [42]:
for i in raw_sent:
    print(simple_preprocess(i))

['once', 'upon', 'time', 'there', 'was', 'young', 'boy', 'named', 'arjun', 'who', 'lived', 'in', 'small', 'town', 'surrounded', 'by', 'hills', 'and', 'rivers']
['he', 'was', 'very', 'curious', 'about', 'how', 'things', 'worked', 'and', 'always', 'asked', 'questions']
['his', 'parents', 'often', 'smiled', 'at', 'his', 'curiosity', 'and', 'encouraged', 'him', 'to', 'learn', 'more']
['every', 'day', 'after', 'school', 'arjun', 'would', 'sit', 'with', 'his', 'books', 'and', 'explore', 'different', 'topics']
['he', 'was', 'especially', 'fascinated', 'by', 'science', 'and', 'technology']
['he', 'wanted', 'to', 'understand', 'how', 'machines', 'think', 'and', 'whether', 'they', 'could', 'become', 'as', 'intelligent', 'as', 'humans']
['one', 'day', 'while', 'browsing', 'through', 'an', 'old', 'computer', 'at', 'school', 'arjun', 'discovered', 'the', 'concept', 'of', 'artificial', 'intelligence']
['he', 'read', 'about', 'how', 'machines', 'can', 'learn', 'from', 'data', 'recognize', 'patterns',

In [43]:
folder_path = r"C:\src\pyprojects\Full-Stack-GenAI-Bootcamp-1.0\04-12-2026\data"
story=[]
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path,filename)
    with open(file_path,encoding='unicode_escape') as f:
        corpus=f.read()
        raw_sent=sent_tokenize(corpus)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))



In [28]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'and',
  'rivers'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'asked',
  'questions'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'learn',
  'more'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['he',
  'was',
  'especially',
  'fascinated',
  'by',
  'science',
  'and',
  'technology'],
 ['he',
  'wanted',
  'to',
  'understand',
  'how',
  'machines',
  'think',
  'and',
  'whether',
  'they',
  'could',
  'become',
  'as',
  'intelligent',
  'as',
  'humans'],
 ['one',
  'day',
  'while',
  'browsing',
  'through',
  'an',
  'old',
  'computer',
  'at',
  'sc

In [29]:
story[0]

['once',
 'upon',
 'time',
 'there',
 'was',
 'young',
 'boy',
 'named',
 'arjun',
 'who',
 'lived',
 'in',
 'small',
 'town',
 'surrounded',
 'by',
 'hills',
 'and',
 'rivers']

In [44]:
story[1]

['he',
 'was',
 'very',
 'curious',
 'about',
 'how',
 'things',
 'worked',
 'and',
 'always',
 'asked',
 'questions']

# Word2vec(...,sg=0) # CBOW #by default
# Word2vec(...,sg=1) # skip-gram

In [56]:
custom_model =gensim.models.Word2Vec(
    window=10,
    min_count=1,
    vector_size=150
)
## these all the value are the hyperparameters

In [57]:
custom_model.build_vocab(story)


In [58]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)

(3371, 5220)

In [59]:
custom_model.wv["arjun"]

array([ 2.6652003e-03,  2.8245403e-03,  6.5046512e-03, -2.9594905e-03,
       -9.7900024e-04, -4.8407973e-03, -6.5083457e-03, -5.5592735e-03,
       -8.9224969e-04, -4.1782702e-03,  3.3547548e-03, -4.0903729e-03,
        1.4304204e-03,  4.5200656e-04, -2.5152317e-03, -9.2202768e-04,
        6.7886058e-03,  6.0640317e-03, -3.1183886e-03,  6.2328507e-03,
       -3.8982404e-03,  3.8104909e-03, -1.7123157e-03,  2.6284952e-03,
        1.9528873e-03,  4.4414029e-03, -1.9265332e-03,  5.5350247e-03,
        4.9215574e-03, -6.6542877e-03, -5.1630284e-03, -5.1484681e-03,
        1.7946371e-03, -2.1244455e-03, -4.9253558e-03, -5.3152777e-03,
        5.9422376e-03,  1.4605242e-03, -6.2021515e-03, -3.4563520e-03,
        2.0429585e-03, -3.1655910e-03,  3.1986262e-03, -2.9756571e-03,
        1.8925727e-03, -5.4666759e-03,  4.1482230e-03,  3.1765231e-03,
        5.7671935e-04,  2.1005478e-03, -5.7784277e-03,  1.4107935e-03,
       -6.5248570e-04, -6.0869828e-03, -6.3044881e-03, -8.4901601e-04,
      

In [51]:
len(custom_model.wv["arjun"])

150

In [61]:
custom_model.wv["farmers"]

array([ 5.3552012e-03,  5.1741251e-03, -3.7444988e-03, -5.3383922e-03,
        5.3446591e-03, -2.4728815e-03, -2.7462593e-03,  5.1985038e-03,
        3.4517427e-03,  2.6663404e-03, -7.2656100e-04,  5.7831742e-03,
        5.4437052e-03,  4.5913379e-03,  5.8574476e-03, -4.0924489e-03,
        7.6572871e-04, -1.1296838e-03,  4.1231043e-03,  6.7220512e-03,
        3.2720149e-03,  2.5860902e-03,  4.6602734e-03,  4.2115678e-03,
       -2.6615884e-05, -5.6931456e-03, -1.7418164e-03,  5.7782629e-03,
       -3.4753229e-03,  4.4435813e-04,  3.3774804e-03, -4.6840506e-03,
        5.3546894e-03,  7.1781990e-04,  1.3665642e-03,  5.5706510e-03,
        1.2574379e-03,  6.7592302e-04, -6.3033001e-03,  6.3908747e-03,
       -6.5778191e-03,  5.6763496e-03,  3.1340546e-03, -1.8878994e-04,
       -5.1870192e-03,  6.1012367e-03, -9.1861980e-04,  3.5516135e-03,
       -2.0211558e-03, -3.2087907e-03,  1.2794635e-04, -5.4150079e-03,
       -4.4867937e-03, -6.1870348e-03,  3.5145783e-03,  3.9377486e-04,
      

In [62]:
custom_model.wv["ai"]

array([ 6.4694928e-03,  4.2867009e-03, -6.2649641e-03, -4.7400910e-03,
       -5.6433072e-03,  2.8647000e-03,  6.0026781e-03, -3.1115666e-03,
       -6.1352323e-03, -7.8951259e-04, -1.7660653e-03,  8.7803073e-04,
        3.3544078e-03,  3.6037175e-04,  2.9718128e-03,  5.9011797e-03,
       -5.0911475e-03,  3.8697177e-03,  2.9713544e-04, -5.2706725e-03,
       -3.7234880e-03,  2.6527690e-03,  5.5481796e-03, -3.9958726e-03,
       -2.9267920e-03, -1.9155407e-03, -2.5687320e-03, -6.6827429e-03,
        9.4977091e-04, -5.2455161e-03, -3.9587040e-03,  2.9066112e-03,
       -3.8739103e-03, -2.2661083e-03,  1.6287505e-04,  6.2918616e-03,
       -3.3590635e-03,  6.7418907e-04, -4.6910672e-03,  4.1232849e-03,
        6.5253787e-03,  6.5594106e-03, -3.0211024e-03,  6.2871967e-03,
        4.8400024e-03, -2.2111238e-04, -2.4065801e-03,  1.0149500e-03,
        2.5681295e-03, -4.8076762e-03,  2.3136477e-03,  2.0338637e-03,
        4.6098503e-04, -1.7656884e-03,  1.6379752e-03,  3.8171078e-03,
      

In [63]:
custom_model.wv.most_similar("arjun")

[('curious', 0.2585282027721405),
 ('healthcare', 0.23024840652942657),
 ('that', 0.2119806557893753),
 ('their', 0.19668042659759521),
 ('predictions', 0.1965198814868927),
 ('how', 0.1962643712759018),
 ('passed', 0.18270263075828552),
 ('improvements', 0.162565216422081),
 ('decided', 0.16041719913482666),
 ('games', 0.15869300067424774)]

In [64]:
custom_model.wv.most_similar("engineer")

[('solve', 0.21200162172317505),
 ('decided', 0.2004907876253128),
 ('boy', 0.19899894297122955),
 ('were', 0.19713957607746124),
 ('build', 0.19529303908348083),
 ('learned', 0.1832837462425232),
 ('refining', 0.1758306920528412),
 ('shared', 0.1707114577293396),
 ('simple', 0.1691044420003891),
 ('named', 0.16117146611213684)]

In [67]:
custom_model.wv.doesnt_match(["arjun","engineer","programming","farmers"])

'arjun'

In [68]:
custom_model.wv.doesnt_match(["weather","crops","farmers","technology"])

'crops'

In [69]:
custom_model.wv.similarity("ai","technology")

np.float32(0.01988266)

In [70]:
custom_model.wv.similarity("arjun","engineer")

np.float32(-0.07584899)

## add more data, train for more epoch
## check the embedding dimension also